apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-pvc
  namespace: enterprise-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2 # Standard AWS EBS class
